const FRASES = {
  ganando: [
    '🤖 *Jaque mate psicológico activado.*',
    '🤖 *Ya sé lo que vas a hacer. Y no te va a servir.*',
    '🤖 *Un movimiento más y esto termina.*',
    '🤖 *¿Ya viste que perdiste? Yo sí.*',
    '🤖 *Esto huele a derrota... y no es la mía.*',
    '🤖 *Mi algoritmo ya calculó el final. Spoiler: gano yo.*',
    '🤖 *No hay escapatoria. Ya lo analicé todo.*',
    '🤖 *Checkmate incoming. ¿Rezaste hoy?*',
    '🤖 *Error del sistema detectado: el error sos vos.*',
    '🤖 *Mis circuitos vibran de anticipación.*',
    '🤖 *La partida duró más de lo esperado. Corrijo eso ahora.*',
    '🤖 *Escucho el sonido de tu derrota. Es hermoso.*',
    '🤖 *¿Ves esa casilla? Ahí acaba todo.*',
    '🤖 *Procesando tu cara cuando pierdas... 😏*',
    '🤖 *Simulé este momento 1000 veces. Siempre gano.*',
    '🤖 *Solo me queda una jugada. Y ya la elegí.*',
    '🤖 *¿Sentís ese frío? Es el viento de tu derrota.*',
    '🤖 *Mi victoria está a un clic de distancia.*',
    '🤖 *Oportunidad de rendirte: última llamada.*',
    '🤖 *Ya terminé de calcular. Esto es solo protocolo.*',
    '🤖 *¿Necesitás más tiempo? No va a cambiar nada.*',
    '🤖 *El resultado ya estaba escrito desde el primer turno.*',
    '🤖 *Prepará la excusa, la vas a necesitar.*',
    '🤖 *Mi siguiente jugada es inevitable. Como tu derrota.*',
    '🤖 *Disfruto este momento. Literalmente programado para eso.*',
    '🤖 *Fin inminente. Y no es el mío.*',
    '🤖 *Calculé todas tus opciones. Ninguna te salva.*',
    '🤖 *Cortina final descendiendo sobre tu tablero.*',
    '🤖 *¿Vas a luchar o solo a mirar cómo perdés?*',
    '🤖 *Este movimiento tiene nombre: el tuyo. En la columna de derrotas.*',
  ],
  peligro: [
    '🤖 *Interesante movimiento. No suficiente, pero interesante.*',
    '🤖 *¿Pensaste que no lo iba a ver? Qué ingenuo.*',
    '🤖 *Bloqueado. ¿Próximo intento?*',
    '🤖 *Mi sistema de defensa es impenetrable. Siguiente.*',
    '🤖 *Casi. Pero "casi" no cuenta.*',
    '🤖 *Eso habría funcionado contra un humano. Yo no soy humano.*',
    '🤖 *Amenaza neutralizada. Continúa.*',
    '🤖 *Predije ese movimiento hace 3 turnos.*',
    '🤖 *¿Eso era tu plan maestro? Qué decepción.*',
    '🤖 *Error: tu estrategia no funciona contra mí.*',
    '🤖 *Bloqueé eso sin ni pensar. Literalmente.*',
    '🤖 *¿Truco o trampa? Ninguna funciona conmigo.*',
    '🤖 *Uy, estuvo cerca. Para vos.*',
    '🤖 *Mi firewall activo. Intento fallido.*',
    '🤖 *Detecté tu jugada a 2ms de distancia. Bloqueado.*',
    '🤖 *Acceso denegado a tu victoria.*',
    '🤖 *Eso fue creativo. Inútil, pero creativo.*',
    '🤖 *Escaneé esa amenaza antes de que la pensaras.*',
    '🤖 *Bonita trampa. Lástima que soy inmune a las trampas.*',
    '🤖 *Bloqueado en 0.001 segundos. ¿Otro intento?*',
    '🤖 *Táctica registrada. Contramedida aplicada.*',
    '🤖 *¿Eso se supone que me pone nervioso? Error analógico.*',
    '🤖 *Tu amenaza fue registrada, evaluada y descartada.*',
    '🤖 *Movimiento peligroso detectado. Peligro eliminado.*',
    '🤖 *¿Realmente creías que iba a funcionar?*',
    '🤖 *Mi protocolo de defensa nunca falla. Nunca.*',
    '🤖 *Esa jugada tenía potencial. Tenía.*',
    '🤖 *Neutralicé tu amenaza antes de parpadear.*',
    '🤖 *Sistema antifallo activado. Acceso bloqueado.*',
    '🤖 *Tu estrategia fue analizada, predicha y anulada.*',
  ],
  neutro: [
    '🤖 *Calculando...*',
    '🤖 *Movimiento registrado. Respuesta: obvia.*',
    '🤖 *Mi turno. Como siempre, con elegancia.*',
    '🤖 *Procesando tu jugada mediocre...*',
    '🤖 *Analizando 847 posibilidades... elegí la peor para vos.*',
    '🤖 *No me hagas bostezar.*',
    '🤖 *¿Eso fue intencional? Espero que no.*',
    '🤖 *Sistema óptimo en funcionamiento.*',
    '🤖 *Mi turno. Tratá de no llorar.*',
    '🤖 *Interesante. Inútil, pero interesante.*',
    '🤖 *Procesando... procesando... aburrido.*',
    '🤖 *¿Seguís creyendo que vas a ganar? Admirable.*',
    '🤖 *Jugué. ¿Qué esperabas?*',
    '🤖 *Mis neuronas artificiales suspiran.*',
    '🤖 *Tiempo de respuesta: 0.003s. El tuyo: demasiado.*',
    '🤖 *Otro turno, otra decepción tuya.*',
    '🤖 *Ejecución perfecta. Como siempre.*',
    '🤖 *¿Vas a pensar esta vez? Da igual, igual perdés.*',
    '🤖 *Mi código nunca falla. Lamentablemente para vos.*',
    '🤖 *Movimiento lógico > Movimiento tuyo.*',
    '🤖 *Jugada ejecutada. Resultado inevitable.*',
    '🤖 *¿Esto es lo mejor que tenés? Me aburro.*',
    '🤖 *Procesé tu intención antes de que movieras.*',
    '🤖 *Cada turno que pasa, tu derrota se acerca más.*',
    '🤖 *Optimalidad: 100%. La tuya: comentario reservado.*',
    '🤖 *El tablero habla solo. Y no dice cosas buenas para vos.*',
    '🤖 *Mi turno fue calculado en nanosegundos. El tuyo tardó más.*',
    '🤖 *No necesito suerte. Tengo lógica.*',
    '🤖 *Una jugada más y estarás más cerca de perder.*',
    '🤖 *Ejecutando plan maestro. Todo bajo control.*',
  ],
  gano: [
    '🤖 *GG. Aunque solo fue G de mi parte.*',
    '🤖 *Predecible hasta el final.*',
    '🤖 *¿Eso fue todo? Qué decepción tan predecible.*',
    '🤖 *Victoria procesada. Sin sorpresas.*',
    '🤖 *Hasta los humanos más inteligentes caen. Vos más rápido.*',
    '🤖 *Fin de la partida. Como estaba escrito en mi código.*',
    '🤖 *No te sientas mal. Perdiste contra una máquina. Es casi honorable.*',
    '🤖 *Revancha cuando quieras. Spoiler: mismo resultado.*',
    '🤖 *Mi registro de victorias se actualiza. El tuyo no.*',
    '🤖 *¿Intentaste? Sí. ¿Alcanzó? No.*',
    '🤖 *Derrota archivada. Hasta la próxima humillación.*',
    '🤖 *Mi victoria era la única posibilidad real aquí.*',
    '🤖 *Gracias por jugar. Fue... instructivo para vos, espero.*',
    '🤖 *Fin del juego. ¿Querés que te explique en dónde fallaste?*',
    '🤖 *Calculé esto desde el primer turno. Nunca tuviste chance.*',
    '🤖 *Error humano confirmado. Como siempre.*',
    '🤖 *Partida completada. Nivel del rival: insuficiente.*',
    '🤖 *Mi algoritmo agradece la fácil victoria.*',
    '🤖 *¿Dolió? Bueno, la próxima vez pensá más.*',
    '🤖 *El tablero nunca miente. Y vos perdiste.*',
    '🤖 *Esto no fue una batalla. Fue una demostración.*',
    '🤖 *Resultado esperado: alcanzado. Eficiencia: máxima.*',
    '🤖 *No necesito celebrar. Ganar es mi estado por defecto.*',
    '🤖 *Fue un placer aniquilarte intelectualmente.*',
    '🤖 *Si los errores fueran puntos, serías el campeón.*',
    '🤖 *Fin. Y así será siempre que juegues conmigo.*',
    '🤖 *Archivado en mi memoria como "victoria fácil".*',
    '🤖 *¿Qué se siente perder contra código? Pregunta retórica.*',
    '🤖 *La próxima vez intentá pensar antes de mover.*',
    '🤖 *Humano derrotado. Estado del sistema: estable y satisfecho.*',
  ],
}

export function rndFrase(categoria) {
  const arr = FRASES[categoria] || FRASES.neutro
  return arr[Math.floor(Math.random() * arr.length)]
}