export const palabras = [

    "gato", "perro", "elefante", "jirafa", "computadora", 
    "teclado", "botella", "montaña", "oceano", "planeta",
    "galaxia", "universo", "estrella", "camion", "bicicleta",
    "guitarra", "piano", "trompeta", "violin", "escuela",
    "trabajo", "programacion", "javascript", "internet", "wifi",
    "telefono", "camara", "videojuego", "pelicula", "cine",
    "teatro", "musica", "pintura", "dibujo", "arte",
    "ciencia", "biologia", "quimica", "fisica", "historia",
    "geografia", "matematicas", "literatura", "idioma", "ingles",
    "español", "frances", "italiano", "aleman", "chino",
    "japones", "coreano", "ruso", "portugues", "arabe",
    "argentina", "mexico", "colombia", "españa", "chile",
    "peru", "ecuador", "venezuela", "bolivia", "uruguay",
    "paraguay", "brasil", "estadosunidos", "canada", "francia",
    "italia", "alemania", "reinounido", "china", "japon",
    "fuego", "agua", "tierra", "aire", "espacio",
    "tiempo", "reloj", "calendario", "semana", "mes",
    "año", "siglo", "milenio", "dia", "noche",
    
    "leon", "tigre", "rinoceronte", "hipopotamo", "cocodrilo",
    "canguro", "koala", "panda", "oso", "lobo", "zorro",
    "aguila", "halcon", "buho", "lechuza", "pinguino",
    "avestruz", "flamenco", "loro", "tucan", "colibri",
    "ballena", "delfin", "tiburon", "pulpo", "medusa",
    "cangrejo", "langosta", "camaron", "tortuga", "serpiente",
    "iguana", "camaleon", "rana", "sapo", "salamandra",
    "abeja", "hormiga", "mariposa", "escarabajo", "araña",
    "escorpion", "ciervo", "cebra", "bufalo", "caballo",
    "burro", "cerdo", "vaca", "oveja", "cabra", "gallina",
    "gallo", "pato", "cisne", "ganzo", "raton", "haster",
    "conejo", "ardilla", "castor", "murcielago", "mapache",
    "gorila", "chimpance", "lemur", "suricata", "nutria",

    // --- COMIDA Y BEBIDA ---
    "manzana", "banana", "naranja", "uva", "frutilla",
    "sandia", "melon", "piña", "mango", "limon", "lima",
    "cereza", "durazno", "ciruela", "kiwi", "papaya",
    "tomate", "lechuga", "zanahoria", "cebolla", "ajo",
    "papa", "batata", "calabaza", "pepino", "pimiento",
    "brocoli", "coliflor", "espinaca", "maiz", "arroz",
    "trigo", "avena", "frijol", "lenteja", "garbanzo",
    "pan", "tostada", "galleta", "pastel", "torta",
    "chocolate", "helado", "caramelo", "chicle", "miel",
    "azucar", "sal", "pimienta", "aceite", "vinagre",
    "carne", "pollo", "pescado", "huevo", "leche",
    "queso", "yogur", "manteca", "hamburguesa", "pizza",
    "pasta", "espagueti", "fideos", "sopa", "ensalada",
    "sushi", "taco", "burrito", "empanada", "asado",
    "cafe", "te", "jugo", "refresco", "agua", "vino",

    "mesa", "silla", "sillon", "sofa", "cama", "almohada",
    "sabana", "cobija", "armario", "ropero", "espejo",
    "lampara", "foco", "vela", "alfombra", "cortina",
    "puerta", "ventana", "techo", "piso", "pared",
    "cocina", "heladera", "nevera", "microondas", "horno",
    "licuadora", "batidora", "tostadora", "plato", "vaso",
    "taza", "cuchara", "tenedor", "cuchillo", "sarten",
    "olla", "escoba", "trapeador", "balde", "esponja",
    "jabon", "shampoo", "toalla", "cepillo", "peine",
    "reloj", "cuadro", "maceta", "florero", "llave",
    "candado", "bolsa", "caja", "maleta", "mochila",

    "camisa", "camiseta", "pantalon", "short", "falda",
    "vestido", "traje", "abrigo", "chaqueta", "sueter",
    "bufanda", "guante", "gorro", "sombrero", "gorra",
    "calcetin", "zapato", "zapatilla", "bota", "sandalia",
    "cinturon", "corbata", "reloj", "anillo", "collar",
    "pulsera", "arete", "lentes", "gafas", "paraguas",

    "doctor", "medico", "enfermero", "dentista", "veterinario",
    "ingeniero", "arquitecto", "abogado", "juez", "policia",
    "bombero", "militar", "detective", "profesor", "maestro",
    "estudiante", "cientifico", "astronauta", "piloto", "capitan",
    "cocinero", "chef", "panadero", "mesero", "carpintero",
    "electricista", "plomero", "mecanico", "pintor", "escritor",
    "periodista", "actor", "actriz", "cantante", "musico",
    "bailarin", "fotografo", "diseñador", "programador", "hacker",

    "bosque", "selva", "desierto", "playa", "mar",
    "rio", "lago", "laguna", "cascada", "volcan",
    "cueva", "isla", "pantano", "jardin", "parque",
    "ciudad", "pueblo", "campo", "granja", "edificio",
    "rascacielos", "casa", "hotel", "hospital", "escuela",
    "universidad", "biblioteca", "museo", "estadio", "aeropuerto",
    "estacion", "puente", "carretera", "calle", "camino",
    "nube", "lluvia", "nieve", "granizo", "tormenta",
    "rayo", "trueno", "viento", "huracan", "tornado",
    "sol", "luna", "estrella", "arcoiris", "aurora",

    "robot", "maquina", "motor", "bateria", "cable",
    "pantalla", "monitor", "teclado", "mouse", "raton",
    "impresora", "escaner", "parlante", "audifono", "microfono",
    "celular", "movil", "tablet", "consola", "control",
    "boton", "antena", "satelite", "cohete", "nave",
    "servidor", "red", "datos", "codigo", "pixel",

    "futbol", "baloncesto", "basquet", "tenis", "voleibol",
    "beisbol", "rugby", "golf", "hockey", "cricket",
    "natacion", "atletismo", "ciclismo", "boxeo", "karate",
    "judo", "esgrima", "surf", "patinaje", "esqui",
    "ajedrez", "cartas", "dados", "rompecabezas", "baile",
    "canto", "lectura", "escritura", "viaje", "pesca",

    "cabeza", "cara", "frente", "ojo", "ceja",
    "pestaña", "nariz", "oreja", "boca", "diente",
    "lengua", "labio", "barbilla", "cuello", "hombro",
    "brazo", "codo", "muñeca", "mano", "dedo",
    "uña", "pecho", "espalda", "estomago", "cintura",
    "cadera", "pierna", "rodilla", "tobillo", "pie",
    "talon", "piel", "hueso", "sangre", "corazon",
    "cerebro", "pulmon", "higado", "riñon", "musculo",

    "lunes", "martes", "miercoles", "jueves", "viernes",
    "sabado", "domingo", "enero", "febrero", "marzo",
    "abril", "mayo", "junio", "julio", "agosto",
    "septiembre", "octubre", "noviembre", "diciembre",
    "primavera", "verano", "otoño", "invierno", "ayer",
    "hoy", "mañana", "mediodia", "medianoche", "madrugada",
    "decada", "eterno", "futuro", "pasado", "presente",

    "rojo", "azul", "verde", "amarillo", "negro",
    "blanco", "gris", "rosa", "violeta", "naranja",
    "celeste", "marron", "turquesa", "dorado", "plateado",
    "circulo", "cuadrado", "triangulo", "rectangulo", "rombo",
    "esfera", "cubo", "piramide", "cono", "cilindro",
    "linea", "punto", "curva", "fondo", "figura",

    "familia", "madre", "padre", "mama", "papa",
    "hermano", "hermana", "abuelo", "abuela", "tio",
    "tia", "primo", "prima", "sobrino", "sobrina",
    "nieto", "nieta", "hijo", "hija", "bebe",
    "padrino", "madrina", "suegro", "suegra", "cuñado",
    "amigo", "amiga", "vecino", "niño", "niña",
    "hombre", "mujer", "anciano", "adulto", "joven",

    "cuaderno", "carpeta", "hoja", "folio", "lapiz",
    "boligrafo", "pluma", "goma", "borrador", "regla",
    "tijera", "pegamento", "clip", "grapadora", "tiza",
    "pizarron", "tablero", "pupitre", "escritorio", "mapa",
    "globo", "diccionario", "enciclopedia", "diploma", "examen",
    "tarea", "leccion", "recreo", "aula", "clase",
    "mochila", "lonchera", "estuche", "cartulina", "marcador",

    "martillo", "clavo", "tornillo", "tuerca", "destornillador",
    "pinza", "alicates", "llave", "sierra", "serrucho",
    "taladro", "broca", "metro", "cinta", "nivel",
    "pala", "pico", "hacha", "ladrillo", "cemento",
    "madera", "metal", "hierro", "acero", "aluminio",
    "vidrio", "cristal", "plastico", "carton", "papel",
    "tela", "lana", "hilo", "aguja", "cuero",

    "dragon", "hada", "duende", "mago", "bruja",
    "gigante", "ogro", "sirena", "unicornio", "monstruo",
    "vampiro", "zombie", "fantasma", "momia", "espiritu",
    "castillo", "palacio", "torre", "trono", "corona",
    "rey", "reina", "principe", "princesa", "caballero",
    "espada", "escudo", "armadura", "casco", "tesoro",
    "moneda", "joya", "diamante", "pocion", "hechizo",

    "taxi", "remis", "ambulancia", "patrulla", "grua",
    "tractor", "tanque", "submarino", "yate", "canoa",
    "balsa", "ferry", "crucero", "trineo", "carreta",
    "monopatin", "patineta", "helicoptero", "avioneta", "jet",
    "semaforo", "acera", "banqueta", "esquina", "avenida",
    "plaza", "fuente", "banco", "correo", "circo",
    "zoologico", "mercado", "supermercado", "tienda", "kiosco",
    "farmacia", "panaderia", "carniceria", "libreria", "jugueteria",

    "raiz", "tronco", "rama", "hoja", "flor",
    "petalo", "polen", "semilla", "fruto", "espina",
    "piedra", "roca", "arena", "polvo", "barro",
    "lodo", "ola", "marea", "orilla", "costa",
    "horizonte", "amanecer", "atardecer", "clima", "temperatura",
    "terremoto", "tsunami", "inundacion", "sequia", "fuego",

    "correr", "saltar", "caminar", "dormir", "soñar",
    "despertar", "comer", "beber", "reir", "llorar",
    "gritar", "callar", "mirar", "ver", "observar",
    "oir", "escuchar", "tocar", "sentir", "oler",
    "amar", "odiar", "querer", "pensar", "saber",
    "aprender", "enseñar", "leer", "escribir", "dibujar",
    "pintar", "jugar", "ganar", "perder", "empatar",
    "abrir", "cerrar", "entrar", "salir", "subir",
    "bajar", "comprar", "vender", "pagar", "regalar",

    "felicidad", "tristeza", "alegria", "enojo", "ira",
    "miedo", "temor", "valor", "coraje", "sorpresa",
    "duda", "certeza", "idea", "mente", "alma",
    "suerte", "destino", "exito", "fracaso", "victoria",
    "derrota", "paz", "guerra", "libertad", "justicia",
    "verdad", "mentira", "secreto", "misterio", "aventura",
    "salud", "enfermedad", "vida", "muerte", "nacimiento"
]